name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  testar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Verificar versão do Node
        run: node -v

      - name: Rodar os testes
        run: node test.js